services:
  - type: web
    name: translation-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "flask run --host=0.0.0.0"
    envVars:
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
